### ISSUE TITLE
Different Booking Entities

### ISSUE THREAD

**Issue by froid1911** [ama3ing/MelifaroBookingBundle#2]
Hi melifaro,

you've developed a gread bundle. But i need the bundle for 2 or evt. more different independent reservation entities. E.G. BikeReservation, CarReservation. 
Do you has an idea, how i can solve this problem? Currently i have to set the entity class in app/config.yml

kind regards,
fussl

**Comment by dialogik** [comment]
Couldn't you simply add a specific property to your entity, such as `reservation_type`? Where the type can either by some string, e.g. `bike`/`car` or an integer like `0` (bike) or `1` (car).
